services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb:inception

    env_file:
      - .env

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ${MYSQL_HOST}

    secrets:
      - db_root_password
      - db_password

    volumes:
      - mariadb:/var/lib/mysql

    networks:
      - inception

    restart: unless-stopped

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb

networks:
  inception:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt